// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using PO03_01.Models;

namespace PO03_01.Data;

public partial class ChinookContext : DbContext
{
    public ChinookContext(DbContextOptions<ChinookContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Album> Albums { get; set; }

    public virtual DbSet<Artist> Artists { get; set; }

    public DbSet<PO03_01.Models.Pedido>? Pedido { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Album>(entity =>
        {
            entity.HasOne(d => d.Artist).WithMany(p => p.Albums).HasConstraintName("FK_AlbumArtistId");
        });

        modelBuilder.Entity<Album>().ToTable("Album", t => t.ExcludeFromMigrations());
        modelBuilder.Entity<Artist>().ToTable("Artist", t => t.ExcludeFromMigrations());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);


}