// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Proyecto_Razor.Models
{
    public partial class Ataques
    {
        public int IdAtaque { get; set; }
        public int IdPokemon { get; set; }
        public string Nombre { get; set; }
    }
}