// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Proyecto_Razor.Models
{
    public partial class MisDatos : DbContext
    {
        public MisDatos()
        {
        }

        public MisDatos(DbContextOptions<MisDatos> options)
            : base(options)
        {
        }

        public virtual DbSet<Ataques> Ataques { get; set; }
        public virtual DbSet<JuegosPokemon> JuegosPokemon { get; set; }
        public virtual DbSet<Pokemon> Pokemon { get; set; }
        public virtual DbSet<Tipos> Tipos { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Ataques>(entity =>
            {
                entity.HasKey(e => e.IdAtaque)
                    .HasName("PK__Ataques__FB8DC5B359C8000B");

                entity.Property(e => e.IdAtaque).HasColumnName("id_ataque");

                entity.Property(e => e.IdPokemon).HasColumnName("id_pokemon");

                entity.Property(e => e.Nombre)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("nombre");
            });

            modelBuilder.Entity<JuegosPokemon>(entity =>
            {
                entity.HasKey(e => e.IdJuego)
                    .HasName("PK__JuegosPo__368EED5062A2DF77");

                entity.Property(e => e.IdJuego)
                    .ValueGeneratedNever()
                    .HasColumnName("id_juego");

                entity.Property(e => e.FechaLanzamiento)
                    .HasColumnType("date")
                    .HasColumnName("fecha_lanzamiento");

                entity.Property(e => e.Nombre)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("nombre");

                entity.Property(e => e.Plataforma)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("plataforma");
            });

            modelBuilder.Entity<Pokemon>(entity =>
            {
                entity.HasKey(e => e.NumeroPokedex)
                    .HasName("PK__Pokemon__D1C5A7D406EFBDB4");

                entity.Property(e => e.NumeroPokedex).HasColumnName("numero_pokedex");

                entity.Property(e => e.Altura)
                    .HasColumnType("decimal(5, 2)")
                    .HasColumnName("altura");

                entity.Property(e => e.EsEvolucion).HasColumnName("es_evolucion");

                entity.Property(e => e.IdTipo).HasColumnName("id_tipo");

                entity.Property(e => e.Nombre)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("nombre");

                entity.Property(e => e.Peso)
                    .HasColumnType("decimal(5, 2)")
                    .HasColumnName("peso");
            });

            modelBuilder.Entity<Tipos>(entity =>
            {
                entity.HasKey(e => e.IdTipo)
                    .HasName("PK__Tipos__CF901089DDE6F64F");

                entity.Property(e => e.IdTipo).HasColumnName("id_tipo");

                entity.Property(e => e.Nombre)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("nombre");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}