// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Proyecto_Razor.Models
{
    public partial class Pokemon
    {
        public int NumeroPokedex { get; set; }
        public string Nombre { get; set; }
        public decimal Peso { get; set; }
        public decimal Altura { get; set; }
        public int IdTipo { get; set; }
        public bool EsEvolucion { get; set; }
    }
}