// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Proyecto_Razor.Models
{
    public partial class Tipos
    {
        public int IdTipo { get; set; }
        public string Nombre { get; set; }
    }
}