//------------------------------------------------------------------------------
// <auto-generated>
//     This xml documentation was generated by CXCommenter: 1.0.0.5.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright file="Program.cs" company="PlaceholderCompany">
//     Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
/// <summary>
///       Namespace Name - Ejercicio.
/// </summary>
namespace Ejercicio
{
    internal class Ejercicio
    {
        /// <summary>
        ///     Function Name - Main.
        /// </summary>
        /// <param name="string[] args">: Describe string[] args here.</param>
        /// <returns>void.</returns>
        static void Main(String[] args)
        {
            string frase = "";
            Console.WriteLine("Escribe una frase");
            frase = Console.ReadLine();
            while (!(frase.Length > 0))
            {
                Console.WriteLine("Tienes que introducir una frase valida");
                frase = Console.ReadLine();
            }
            for (int i = frase.Length - 1; i >= 0; i--)
                Console.WriteLine("\t{0}", frase[i]);
        }
    }
}


