// <auto-generated />
using AUT03_02.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AUT03_02.Migrations
{
    [DbContext(typeof(VideogamesContext))]
    [Migration("20231113210118_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AUT03_02.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreId = 1,
                            Name = "The Last of Us"
                        },
                        new
                        {
                            Id = 2,
                            GenreId = 1,
                            Name = "God of War"
                        },
                        new
                        {
                            Id = 3,
                            GenreId = 2,
                            Name = "The Legend of Zelda: Breath of the Wild"
                        },
                        new
                        {
                            Id = 4,
                            GenreId = 2,
                            Name = "Uncharted 4: A Thief's End"
                        },
                        new
                        {
                            Id = 5,
                            GenreId = 3,
                            Name = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = 6,
                            GenreId = 3,
                            Name = "Elder Scrolls V: Skyrim"
                        });
                });

            modelBuilder.Entity("AUT03_02.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Acción"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Aventuras"
                        },
                        new
                        {
                            Id = 3,
                            Name = "RPG"
                        });
                });

            modelBuilder.Entity("AUT03_02.Models.Game", b =>
                {
                    b.HasOne("AUT03_02.Models.Genre", "Genre")
                        .WithMany("Game")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("AUT03_02.Models.Genre", b =>
                {
                    b.Navigation("Game");
                });
#pragma warning restore 612, 618
        }
    }
}
