//------------------------------------------------------------------------------
// <auto-generated>
//     This xml documentation was generated by CXCommenter: 1.0.0.5.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright file="Program.cs" company="PlaceholderCompany">
//     Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
/// <summary>
///       Namespace Name - Ejercicio.
/// </summary>
namespace Ejercicio
{
    class Ejercicio
    {
        /// <summary>
        ///     Function Name - Main.
        /// </summary>
        /// <param name="string[] args">: Describe string[] args here.</param>
        /// <returns>void.</returns>
        static void Main(String[] args)
        {
            int contador = 0;
            char letra;
            string frase;
            Console.WriteLine("Escribe una frase");
            frase = Console.ReadLine();
            while (!(frase.Length > 0))
            {
                Console.WriteLine("Tienes que introducir una frase valida");
                frase = Console.ReadLine();
            }
            Console.WriteLine("Escribe una letra");
            while (!(Char.TryParse(Console.ReadLine(), out letra)))
                Console.WriteLine("Tienes que introducir una letra valida");
            for (int i = 0; i < frase.Length; i++)
            {
                if (frase[i] == letra)
                {
                    contador++;
                }
            }
            Console.WriteLine("\t La letra {0} sale {1} veces", letra, contador);
        }
    }
}


