//------------------------------------------------------------------------------
// <auto-generated>
//     This xml documentation was generated by CXCommenter: 1.0.0.5.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright file="Program.cs" company="PlaceholderCompany">
//     Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
/// <summary>
///       Namespace Name - Ejercicio.
/// </summary>
namespace Ejercicio
{
    internal class Ejercicio
    {
        /// <summary>
        ///     Function Name - Main.
        /// </summary>
        /// <param name="string[] args">: Describe string[] args here.</param>
        /// <returns>void.</returns>
        static void Main(String[] args)
        {
            string frase = "";
            string noespacios = "";
            char espacio = (char)32;
            bool novalido = false;
            do
            {
                Console.WriteLine("Introduce tu frase");
                frase = Console.ReadLine();
                if (frase != "")
                    novalido = true;
                else
                    Console.WriteLine("La cadena debe tener texto, vuelve a probar");
            } while (!novalido);


            int contador = frase.Length;
            while (frase[contador - 1] == espacio)
                contador--;
            for (int i = 0; i < contador; i++)
                noespacios += frase[i];




            Console.WriteLine(noespacios + "prueba");
        }
    }
}


