//------------------------------------------------------------------------------
// <auto-generated>
//     This xml documentation was generated by CXCommenter: 1.0.0.5.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright file="Program.cs" company="PlaceholderCompany">
//     Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
/// <summary>
///       Namespace Name - Ejercicio.
/// </summary>
namespace Ejercicio
{
    class Ejercicio
    {
        /// <summary>
        ///     Function Name - Main.
        /// </summary>
        /// <param name="string[] args">: Describe string[] args here.</param>
        /// <returns>void.</returns>
        static void Main(String[] args)
        {
            int contador = 0;
            string contraseña = "Eureka";
            string frase = "";
            while (!(contador == 3) && (!(frase == contraseña)))
            {
                Console.WriteLine("Escribe la contraseña");
                frase = Console.ReadLine();
                contador++;
                if (contador == 3 && (!(frase == contraseña)))
                    Console.WriteLine("Has agotado tus tres intentos");
            }
        }
    }
}
