// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using AUT02_04.Models;

namespace AUT02_04.Data
{
    public partial class ChinookContext : DbContext
    {
        public ChinookContext()
        {
        }

        public ChinookContext(DbContextOptions<ChinookContext> options)
            : base(options)
        {
        }


        public virtual DbSet<Album> Albums { get; set; }
        public virtual DbSet<Artist> Artists { get; set; }
        public virtual DbSet<Track> Tracks { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Album>(entity =>
            {
                entity.HasOne(d => d.Artist)
                    .WithMany(p => p.Albums)
                    .HasForeignKey(d => d.ArtistId)
                    .HasConstraintName("FK_AlbumArtistId");
            });

            modelBuilder.Entity<Album>().ToTable("Album", t => t.ExcludeFromMigrations());


            modelBuilder.Entity<Track>(entity =>
            {
                entity.Property(e => e.TrackId).ValueGeneratedNever();

                entity.HasOne(d => d.Album)
                    .WithMany(p => p.Tracks)
                    .HasForeignKey(d => d.AlbumId)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK_TrackAlbumId");
            });


            modelBuilder.Entity<Track>().ToTable("Track", t => t.ExcludeFromMigrations());

            modelBuilder.Entity<Artist>().ToTable("Artist", t => t.ExcludeFromMigrations());

            modelBuilder.Entity<Review>().HasData(
                new Review { Id = 123, Title = "Review 1", Description = "Primera Review", Value = 5, ArtistId = 155 },
                new Review { Id = 223, Title = "Review 2", Description = "Canta feo", Value = 1, ArtistId = 155 },
                new Review { Id = 323, Title = "Review 3", Description = "Who", Value = 4, ArtistId = 212 }
            );


            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

        public DbSet<AUT02_04.Models.Review>? Review { get; set; }
    }
}