// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using AUT02_04_Login.Models;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;

namespace AUT02_04_Login.Data
{
    public partial class NorthwindContext : IdentityDbContext
    {
        public NorthwindContext()
        {
        }

        public NorthwindContext(DbContextOptions<NorthwindContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Shipper> Shippers { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            OnModelCreatingPartial(modelBuilder);
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<Shipper>().ToTable(nameof(Shipper), t => t.ExcludeFromMigrations());
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}