// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using AUT02_03_Hybrid.Models;

namespace AUT02_03_Hybrid.Data
{
    public partial class NorthwindContext : DbContext
    {
        public NorthwindContext()
        {
        }

        public NorthwindContext(DbContextOptions<NorthwindContext> options)
            : base(options)
        {
        }


        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Shipper> Shippers { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            OnModelCreatingPartial(modelBuilder);
            modelBuilder.Entity<Shipper>().HasData(
            new Shipper { ShipperID = 1, CompanyName = "Shipper 1", Phone = "123-456-7890" },
            new Shipper { ShipperID = 2, CompanyName = "Shipper 2", Phone = "987-654-3210" }
            );

            modelBuilder.Entity<Company>().HasData(
            new Company { Id = 1, Name = "Company 1", Description = "Description 1", ShipperID = 1},
            new Company { Id = 2, Name = "Company 2", Description = "Description 2", ShipperID = 1 },
            new Company { Id = 3, Name = "Company 3", Description = "Description 3", ShipperID = 2}
            );
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}